name: dirbbox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^3.0.3
  footer: ^0.0.4
  get: 4.6.5
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
